website/Controllers/ApiController.cs
using Newtonsoft.Json.Linq;
using Octokit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using website.Utils;

namespace website.Controllers
{
    public class ApiController : Controller
    {
        /// <summary>
        /// Return list of repositories
        /// </summary>
        /// <param name="period">0 - weekly; 1 - monthly</param>
        /// <param name="type">0 - stars; 1 - contributors; 2 - commits</param>
        /// <returns>Repositories in json</returns>
        public async Task<string> Repositories(int period, int type)
        {
            var repositories = await CacheService.GetRepositories();
            Dictionary<string, int> sortDictionary = new Dictionary<string, int>();
            if (type == 0)
            {               
                repositories.ToList().ForEach(async repo =>
                {                    
                    var stargazers =  await CacheService.GetStargazers(repo.FullName, period);
                    sortDictionary.Add(repo.FullName, stargazers.Count());
                });                
            }
            else if (type == 1)
            {
                repositories.ToList().ForEach(async repo =>
                {
                    var commits = await CacheService.GetCommits(repo.FullName, period);
                    sortDictionary.Add(repo.FullName, commits.GroupBy(c => c.Committer != null ? c.Committer.Id : 0).Count());
                });
            }
            else if (type == 2)
            {
                repositories.ToList().ForEach(async repo =>
                {
                    var commits = await CacheService.GetCommits(repo.FullName, period);
                    sortDictionary.Add(repo.FullName, commits.Count());
                });
            }
            else
            {
                return "error";
            }

            repositories = repositories.OrderBy(repo => sortDictionary[repo.FullName]).ToList();
            return JObject.FromObject(new
            {
                data = repositories.Select(repository => new string[]{
                repository.FullName,
                repository.Description,
                repository.Language,
                repository.StargazersCount.ToString()
            })
            }).ToString();
        }

        public async Task<string> GetStargazers(string name, int type)
        {
            var stargazers = await CacheService.GetStargazers(name, type);


            var result = stargazers.GroupBy(star =>
                DateTime.Parse(star.StarredAt.ToString()).ToShortDateString())
                .Select(group => new
                {
                    date = group.Key,
                    stars = group.Count()
                }).OrderBy(x => DateTime.Parse(x.date));

            return JObject.FromObject(new
            {
                days = result.Select(r => r.date).ToArray(),
                stars = result.Select(r => r.stars).ToArray()
            }).ToString();
        }

        public async Task<string> GetCommits(string name, int type)
        {
            var commits = await CacheService.GetCommits(name, type);
            var result = commits.GroupBy(commit =>
                DateTime.Parse(commit.Commit.Committer.Date.ToString()).ToShortDateString())
                .Select(group => new
                {
                    date = group.Key,
                    commits = group.Count()
                }).OrderBy(x => DateTime.Parse(x.date));

            return JObject.FromObject(new
            {
                days = result.Select(r => r.date).ToArray(),
                commits = result.Select(r => r.commits).ToArray()
            }).ToString();
        }

        public async Task<string> GetContributors(string name, int type)
        {
            var commits = await CacheService.GetCommits(name, type);
            var result = commits.GroupBy(commit =>
                DateTime.Parse(commit.Commit.Committer.Date.ToString()).ToShortDateString())
                .Select(group => new
                {
                    date = group.Key,
                    contributors = group.GroupBy(commit =>
                        commit.Author.Id).Count()
                }).OrderBy(x => DateTime.Parse(x.date));

            return JObject.FromObject(new
            {
                days = result.Select(r => r.date).ToArray(),
                contributors = result.Select(r => r.contributors).ToArray()
            }).ToString();
        }

        /// <summary>
        /// Check for rate limits
        /// </summary>
        /// <returns>true - rate limits enought, false - rate limits finished</returns>
        public async Task<string> IsRateLimitsValid()
        {
            var limits = await GitHubClientSingelton.Client.Miscellaneous.GetRateLimits();
            /*
           
             * */
            return (limits.Rate.Remaining != 0 &&
                limits.Resources.Core.Remaining != 0 &&
                limits.Resources.Search.Remaining != 0).ToString();
        }
        public async Task<string> RateLimits()
        {
            var limits = await GitHubClientSingelton.Client.Miscellaneous.GetRateLimits();
            return String.Format(
                "Rate(Limit:{0}, Remaining:{1})<br/>" +
                "Core(Limit:{2}, Remaining:{3})<br/>" +
                "Search(Limits:{4}, Remaining:{5})<br/>",
                limits.Rate.Limit, limits.Rate.Remaining,
                limits.Resources.Core.Limit, limits.Resources.Core.Remaining,
                limits.Resources.Search.Limit, limits.Resources.Search.Remaining);
        }
    }
}

website/Controllers/HomeController.cs
using Newtonsoft.Json.Linq;
using Octokit;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using website.Utils;

namespace website.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Repositories()
        {  
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Repository(string name)
        {
            if (name == null)
                return View("Error");

            var repository = await CacheService.GetRepositoryDetails(name);
            return View(JObject.FromObject(repository));
        }

        [HttpGet]
        public ActionResult Organizations()
        {
            return View();
        }

        public async Task<ActionResult> Authorize(string code, string state)
        {
            if (!String.IsNullOrEmpty(code))
            {
                var expectedState = Session["CSRF:State"] as string;
                if (state != expectedState) throw new InvalidOperationException("SECURITY FAIL!");
                Session["CSRF:State"] = null;

                var token = await GitHubClientSingelton.Client.Oauth.CreateAccessToken(
                    new OauthTokenRequest(GitHubClientSingelton.ClientId, GitHubClientSingelton.ClientSecret, code)
                    {
                        RedirectUri = new Uri("http://webchallengeapp.azurewebsites.net/Home/Authorize")
                    });
                Session["OAuthToken"] = token.AccessToken;
                GitHubClientSingelton.Client.Credentials = new Credentials(token.AccessToken);
                return RedirectToAction("Index");
            }

            return Redirect(GetOauthLoginUrl());
        }

        private string GetOauthLoginUrl()
        {
            string csrf = Membership.GeneratePassword(24, 1);
            Session["CSRF:State"] = csrf;

            var request = new OauthLoginRequest(GitHubClientSingelton.ClientId)
            {
                Scopes = { "public_repo"},
                State = csrf
            };
            var oauthLoginUrl = GitHubClientSingelton.Client.Oauth.GetGitHubLoginUrl(request);
            return oauthLoginUrl.ToString();
        }
    }
}

website/Views/Home/Index.cshtml
<br />
<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <h5>Введіть повну назву репозиторія, що вас цікавить:</h5>
        <div class="input-group">            
            @Html.TextBox("name", "", new { @class = "form-control" })
            <span class="input-group-btn">
                <a class="btn btn-default" onclick="submit()">Знайти</a>
            </span>
        </div>
    </div>
</div>
<script type="text/javascript">
    function submit() {
        window.location = '@Url.Action("Repository", "Home")' + '?name=' + $('#name').val();
    };
</script>

website/Views/Home/Organizations.cshtml
<div class="alert-danger text-center">
    <h1>
        Не реалізовано<br />
        </h1>
    <h3>
        Нажаль не встиг
    </h3>
</div>

website/Views/Home/Repositories.cshtml
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js" type="text/javascript"></script>
<style type="text/css">
    .glyphicon-refresh-animate {
        -animation: spin .7s infinite linear;
        -webkit-animation: spin2 .7s infinite linear;
    }

    @@-webkit-keyframes spin2 {
        from {
            -webkit-transform: rotate(0deg);
        }

        to {
            -webkit-transform: rotate(360deg);
        }
    }

    @@keyframes spin {
        from {
            transform: scale(1) rotate(0deg);
        }

        to {
            transform: scale(1) rotate(360deg);
        }
    }
</style>
<br />
<h1>Репозиторії</h1>
<div class="pull-right">
        <div id="loader">
            <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>
            Зачекайте, це займе деякий час...
        </div>
        Сортувати по @Html.DropDownList("type", new List<SelectListItem>
{
    new SelectListItem(){
        Text = "зірочкам",
        Value = "0"
    },
    new SelectListItem(){
            Text = "котриб'юторам",
            Value = "1"
    },
    new SelectListItem(){
            Text = "комітам",
            Value = "2"
    }
})
        за
        @Html.DropDownList("period", new List<SelectListItem>
{
    new SelectListItem(){
        Text = "тиждень",
        Value = "0"
    },
    new SelectListItem(){
            Text = "місяць",
            Value = "1"
    }
})
</div>
<table id="table" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Назва</th>
            <th>Опис</th>
            <th>Мова</th>
            <th>Зірочок</th>
        </tr>
    </thead>
</table>

<script type="text/javascript">
    $.extend($.fn.dataTable.defaults, {
        searching: false,
        ordering: false
    });

    var table = $("#table").on('xhr.dt', function ( e, settings, json, xhr ) {
        $('#loader').hide();
    } ).DataTable({
        "ajax": "@Url.Action("Repositories", "Api")" + "?period=0&type=0",
        "language": {
            "lengthMenu": "Відображати _MENU_ записів на сторінці",
            "zeroRecords": "Вибачте, немає що відображати",
            "info": "Сторінка _PAGE_ з _PAGES_",
            "infoEmpty": "Немає доступних записів"
        }
    });
    $(document).ready(function () {
        $('#table').on('click', 'tr', function () {
            location.href = '@Url.Action("Repository", "Home")' + '?name=' + $('td:first', this).text();
        });
    });

    $('#period').change(function () {
        update();
    });

    $('#type').change(function () {
        update();
    });
    
    function update() {
        var period = $('#period').children(":selected").attr("value");
        var type = $('#type').children(":selected").attr("value");        
        table.ajax.url("@Url.Action("Repositories", "Api")" + "?period=" + period + "&type=" + type).load();        
        $('#loader').show();
    }
</script>

website/Views/Home/Repository.cshtml
@using Newtonsoft.Json.Linq
@model JObject
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<style type="text/css">
    .glyphicon-refresh-animate {
        -animation: spin .7s infinite linear;
        -webkit-animation: spin2 .7s infinite linear;
    }

    @@-webkit-keyframes spin2 {
        from {
            -webkit-transform: rotate(0deg);
        }

        to {
            -webkit-transform: rotate(360deg);
        }
    }

    @@keyframes spin {
        from {
            transform: scale(1) rotate(0deg);
        }

        to {
            transform: scale(1) rotate(360deg);
        }
    }
</style>
<div>
    <h1 class="page-header"><a href="@Model["HtmlUrl"]">@Model["FullName"]</a></h1>
    <h2><span class="glyphicon glyphicon-star"></span><span>&ensp;@Model["StargazersCount"]</span></h2>
    <h2>Мова: @Model["Language"]</h2>
</div>
<br />
<br />
<br />
<div class="pull-right" style="padding-right:10px">
    <div id="loader">
        <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>
        Зачекайте, це займе деякий час...
    </div>
    Побудувати діаграми за останній @Html.DropDownList("period", new List<SelectListItem>
{
    new SelectListItem(){
        Text = "тиждень",
        Value = "0"
    },
    new SelectListItem(){
            Text = "місяць",
            Value = "1"
    }
})
    <br />
</div>
<div id="stars" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<br />
<div id="contributors" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<br />
<div id="commits" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script type="text/javascript">
    $(function (id) {
        update(0);
        $("#period").change(function () {
            var val = $(this).children(":selected").attr("value");
            update(val);
        });
    });

    function update(type) {
        $('#loader').show();
        var status = 0;
        //stars
        $.getJSON('@Url.Action("GetStargazers", "Api", new {name = Model["FullName"]})&type=' + type, function (data) {

            $('#stars').highcharts({
                chart: {
                    zoomType: 'x'
                },
                title: {
                    text: 'Зірочок'
                },
                subtitle: {
                    text: document.ontouchstart === undefined ?
                            'Натисніть та перетягуйте на графіку для збільшення' : 'Натисніть на графік для збільшення'
                },
                xAxis: {
                    type: 'datetime',
                    categories: data.days
                },
                yAxis: {
                    title: {
                        text: 'Зірочок'
                    }
                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    area: {
                        fillColor: {
                            linearGradient: {
                                x1: 0,
                                y1: 0,
                                x2: 0,
                                y2: 1
                            },
                            stops: [
                                [0, Highcharts.getOptions().colors[0]],
                                [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                            ]
                        },
                        marker: {
                            radius: 2
                        },
                        lineWidth: 1,
                        states: {
                            hover: {
                                lineWidth: 1
                            }
                        },
                        threshold: null
                    }
                },

                series: [{
                    type: 'area',
                    name: 'Зірочок',
                    data: data.stars
                }]
            });
        })
            .done(function () {
                loaderChanger();
        });
        //contributors
        $.getJSON('@Url.Action("GetContributors", "Api", new {name = Model["FullName"]})&type=' + type, function (data) {

            $('#contributors').highcharts({
                chart: {
                    zoomType: 'x'
                },
                title: {
                    text: 'Унікальних контриб\'юторів'
                },
                subtitle: {
                    text: document.ontouchstart === undefined ?
                            'Натисніть та перетягуйте на графіку для збільшення' : 'Натисніть на графік для збільшення'
                },
                xAxis: {
                    type: 'datetime',
                    categories: data.days
                },
                yAxis: {
                    title: {
                        text: 'Унікальних контриб\'юторів'
                    }
                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    area: {
                        fillColor: {
                            linearGradient: {
                                x1: 0,
                                y1: 0,
                                x2: 0,
                                y2: 1
                            },
                            stops: [
                                [0, Highcharts.getOptions().colors[0]],
                                [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                            ]
                        },
                        marker: {
                            radius: 2
                        },
                        lineWidth: 1,
                        states: {
                            hover: {
                                lineWidth: 1
                            }
                        },
                        threshold: null
                    }
                },

                series: [{
                    type: 'area',
                    name: 'Котриб\'юторів',
                    data: data.contributors
                }]
            });
        })
            .done(function () {
                loaderChanger();
        });
        //commits
        $.getJSON('@Url.Action("GetCommits", "Api", new {name = Model["FullName"]})&type=' + type, function (data) {

            $('#commits').highcharts({
                chart: {
                    zoomType: 'x'
                },
                title: {
                    text: 'Комітів'
                },
                subtitle: {
                    text: document.ontouchstart === undefined ?
                            'Натисніть та перетягуйте на графіку для збільшення' : 'Натисніть на графік для збільшення'
                },
                xAxis: {
                    type: 'datetime',
                    categories: data.days
                },
                yAxis: {
                    title: {
                        text: 'Комітів'
                    }
                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    area: {
                        fillColor: {
                            linearGradient: {
                                x1: 0,
                                y1: 0,
                                x2: 0,
                                y2: 1
                            },
                            stops: [
                                [0, Highcharts.getOptions().colors[0]],
                                [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                            ]
                        },
                        marker: {
                            radius: 2
                        },
                        lineWidth: 1,
                        states: {
                            hover: {
                                lineWidth: 1
                            }
                        },
                        threshold: null
                    }
                },

                series: [{
                    type: 'area',
                    name: 'Комітів',
                    data: data.commits
                }]
            });
        })
            .done(function () {
                loaderChanger();
            });
        function loaderChanger() {
            status += 1;
            if (status === 3)
                $('#loader').hide();
        }
    }
</script>

website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Головна", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Проекти", "Repositories", "Home")</li>
                    <li>@Html.ActionLink("Організації", "Organizations", "Home")</li>
                    @if (Session["OAuthToken"] == null)
                    {
                        <li>@Html.ActionLink("Авторизуватись", "Authorize", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (Session["OAuthToken"] == null)
        {
            <div>
                <span class="alert-danger"> Авторизуйтесь для підвищення лімітів</span>
            </div>
        }
        <div id="limitAlert">
            <span class="alert-danger"> Ви вичерпали ліміт запитів, зачекайте деякий час</span>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $('#limitAlert').hide();
        $(document).ready(function () {
            $.ajax('@Url.Action("IsRateLimitsValid", "Api")').done(function (data) {
                if(data == "False")
                {
                    $('#limitAlert').show();
                }
            });
        });
    </script>
</body>
</html>